name: Update GitHub Actions

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  update:
    name: Update Actions
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00  # v6.0.0
        with:
          go-version: '1.25.0'
          check-latest: true

      - name: Build updater
        run: make build

      - name: Run updater
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          OWNER: ThreatFlux
          REPO_NAME: ${{ github.event.repository.name }}
        run: ./bin/ghactions-updater -owner ThreatFlux -repo . -repo-name githubWorkFlowChecker

